# Используем CPU-версию PyTorch
ARG PYTORCH="2.0.1"
FROM pytorch/pytorch:latest

env DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y tzdata && \
    ln -fs /usr/share/zoneinfo/Europe/Moscow /etc/localtime && \
    dpkg-reconfigure --frontend noninteractive tzdata

# Обновление и установка зависимостей
RUN apt-get update && apt-get install -y \
    git ninja-build \
    libglib2.0-0 libsm6 libxrender-dev libxext6 libgl1-mesa-glx \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Установка xtcocotools
RUN pip install cython
RUN pip install xtcocotools

# Установка MMEngine и MMCV
RUN pip install openmim
RUN mim install mmengine "mmcv>=2.0.0"

# Установка MMPose
RUN conda clean --all
RUN git clone https://github.com/open-mmlab/mmpose.git /mmpose
WORKDIR /mmpose
RUN git checkout main
RUN pip install -r requirements/build.txt
RUN pip install --no-cache-dir -e .

# Установка дополнительных модулей

RUN apt-get update && \
    apt-get install -y build-essential g++ && \
    apt-get clean
    
RUN pip install numpy==1.26.4
RUN mim install "mmdet>=3.1.0"

# Удаление флагов и переменных CUDA (они больше не нужны)
ENV FORCE_CUDA="0"